### ISSUE TITLE
clearModuleCache hook never runs

### ISSUE THREAD

**Issue by outflux3** [justb3a/processwire-facebookevents#1]
the hooks in the init() never seem to run, so the cache never clears, consequently when users add new items to facebook, the items never appear on their site. I have tried to test the hook and have not been able to verify if the hook ever runs, for example when saving the module, shouldn't the cache clear?
the only way I could get the user's events to appear was to comment out around line 107, this:
$json = $this->cache->get(self::CACHE_KEY);
, reload the page, and then uncomment the line..

**Comment by justb3a** [comment]
You're right, the module has to be flagged as **autoload**, otherwise the `init` function won't be executed. I added the autoload flag, make sure to refresh the module cache after updating the module.

**Comment by outflux3** [comment]
thanks!!!
